<a href="https://colab.research.google.com/github/DrDAN6770/DataSciense-with-Python/blob/main/%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E5%B7%A5%E5%85%B7%E7%AE%B1/%E6%95%99%E7%B7%B4%E5%B8%B6%E8%B7%91/Task%2002/Numpy%E8%88%87Pandas%E5%A5%97%E4%BB%B6%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://dscareer.kolable.app/programs/9bb10c37-9d10-4dc8-9350-3b21b06b1b44/contents/f4757196-ab78-410a-b4ef-93afd9546fe8?back=members_682cf17c-09e2-4154-bf2d-243d99382c1f

#Pandas 簡介與安裝

In [ ]:
# 安裝 Pandas
!pip install pandas

# 匯入 Pandas
import pandas as pd

Pandas 是一個 Python 的資料分析套件，提供了高效的資料結構，方便快速地進行資料處理和分析。

Pandas 套件主要有幾種資料結構：Series 和 DataFrame、Panel（少用）。其中，Series 可以視為**一維的陣列**，每個元素有一個對應的索引；DataFrame 則是一個**二維的表格**，每列和每欄都有一個對應的索引。

* Series：一維陣列，類似於帶有標籤的陣列。
* DataFrame：二維表格，類似於 Excel 表格或 SQL 資料表。
* Panel：三維數據，不常用。

![image.png]()

#建立Pandas物件與外部資料存取

##Series 物件

In [1]:
import pandas as pd

# 創建一個Series物件
s = pd.Series([1, 3, 5, 7, 9])

# Series物件的索引是從 0 開始的整數，可以通過索引來訪問Series物件中的元素。
print(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64

##DataFrame物件

In [2]:
# 創建一個DataFrame物件
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
        'age': [25, 32, 18, 47],
        'city': ['New York', 'Paris', 'London', 'Berlin']}

df = pd.DataFrame(data)

# DataFrame物件的列可以通過列名訪問，行可以通過索引或標籤訪問。
print(df)

      name  age      city
0    Alice   25  New York
1      Bob   32     Paris
2  Charlie   18    London
3    David   47    Berlin

##外部資料存取

---

Pandas 支援各種外部資料存取，如 CSV、Excel、SQL、JSON 等，讀取不同格式文件可以這樣做：

In [ ]:
# 讀取CSV文件
df = pd.read_csv('data.csv')
# 讀取Excel文件
df = pd.read_excel('data.xlsx')

print(df)

#Series、DataFrame 的屬性

##Series物件的屬性

---

Series物件有一些常用的屬性，包括values、index、dtype和shape等。

* values屬性返回Series物件中的元素
* index屬性返回索引
* dtype屬性返回數據類型
* shape屬性返回數據形狀

In [4]:
# 創建一個Series物件
s = pd.Series([1, 3, 5, 7, 9])

# 訪問Series物件的屬性
print(s.values)   # [1 3 5 7 9]
print(s.index)    # RangeIndex(start=0, stop=5, step=1)
print(s.dtype)    # int64
print(s.shape)    # (5,)

[1 3 5 7 9]
RangeIndex(start=0, stop=5, step=1)
int64
(5,)

##DataFrame物件的屬性

---

DataFrame物件有一些常用的屬性，包括values、index、columns、dtype和shape等。
* values屬性返回DataFrame物件中的元素
* index屬性返回行索引
* columns屬性返回列索引
* dtype屬性返回數據類型
* shape屬性返回數據形狀

In [5]:
# 創建一個DataFrame物件
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
     'age': [25, 32, 18, 47],
     'city': ['New York', 'Paris', 'London', 'Berlin']}

df = pd.DataFrame(data)

# 訪問DataFrame物件的屬性
print(df.values)

[['Alice' 25 'New York']
 ['Bob' 32 'Paris']
 ['Charlie' 18 'London']
 ['David' 47 'Berlin']]

In [6]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)

In [7]:
print(df.columns)

Index(['name', 'age', 'city'], dtype='object')

In [8]:
print(df.dtypes)

name    object
age      int64
city    object
dtype: object

In [9]:
print(df.shape)

(4, 3)

###DataFrame 的資料選取

---

DataFrame物件支持多種資料選取方式，包括列選取、行選取和切片選取等。其中列選取和行選取是最常用的資料選取方式

####第一種方式「行選取」可以通過欄位進行選取

In [11]:
# 創建一個DataFrame物件
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
     'age': [25, 32, 18, 47],
     'city': ['New York', 'Paris', 'London', 'Berlin']}

df = pd.DataFrame(data)

# 通過列名選取列
print(df['name'])

0      Alice
1        Bob
2    Charlie
3      David
Name: name, dtype: object

In [12]:
# 也可以利用切片進行多行選取
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
        'age': [25, 32, 18, 47],
        'city': ['New York', 'Paris', 'London', 'Berlin']}

df = pd.DataFrame(data)

# 通過列名選取多列
print(df[['name', 'city']])

      name      city
0    Alice  New York
1      Bob     Paris
2  Charlie    London
3    David    Berlin

####第二種方式「列選取」可以通過索引名稱或索引進行選取

In [14]:
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
     'age': [25, 32, 18, 47],
     'city': ['New York', 'Paris', 'London', 'Berlin']}

df = pd.DataFrame(data)

# 通過行索引選取
print(df[0:3])

      name  age      city
0    Alice   25  New York
1      Bob   32     Paris
2  Charlie   18    London

In [15]:
# 或是利用索引名稱進行選取

df.set_index('name', inplace=True)
print(df['Alice':'Charlie'])

         age      city
name
Alice     25  New York
Bob       32     Paris
Charlie   18    London

####DataFrame 支援一種用座標方式的二維選取

---

以上兩種方法一次選取都只能考慮一個維度

.loc」是一個用於基於標籤（label）選擇行和列的方法，其中 .loc 用於純粹的標籤索引即行和列的名稱，基本語法如下

    df.loc[row_indexer, column_indexer]



*   row_indexer : 選擇行的標籤
*   column_indexer : 選擇列的標籤



---

這兩個參數都可以是一個標籤（單一標籤），也可以是一個標籤列表（多個標籤）。

當 row_indexer 和 column_indexer 都是標籤列表時，返回的是一個子 DataFrame。假設有以下的 DataFrame

In [24]:
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
     'age': [25, 32, 18, 47],
     'city': ['New York', 'Paris', 'London', 'Berlin']}
df = pd.DataFrame(data)
df.set_index('name', inplace=True)

# 選取 "Alice" 和 "Charlie" 兩行的 "age" 和 "city" 這兩列
result = df.loc[['Alice', 'Charlie'], ['age', 'city']]
print(result)

         age      city
name
Alice     25  New York
Charlie   18    London

####遮罩選取

---

遮罩選取指的是根據一個或多個條件建立一個布林遮罩，然後用這個遮罩選取DataFrame中的數據

In [30]:
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
     'age': [25, 32, 18, 47],
     'city': ['New York', 'Paris', 'London', 'Berlin']}
df = pd.DataFrame(data)
df

      name  age      city
0    Alice   25  New York
1      Bob   32     Paris
2  Charlie   18    London
3    David   47    Berlin

In [28]:
# 使用遮罩選取
mask = df['age'] > 30  # 創建一個年齡大於30的遮罩
print(df[mask])

    name  age    city
1    Bob   32   Paris
3  David   47  Berlin

In [31]:
mask = (df['age'] > 30) & (df['city'] == 'Paris')  # 創建一個年齡大於30且城市為Paris的遮罩
print(df[mask])

  name  age   city
1  Bob   32  Paris

###DataFrame 的算術運算與排序

---

DataFrame物件支持多種算術運算，包括加法、減法、乘法和除法等

In [33]:
# 創建兩個DataFrame物件
data1 = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
      'age': [25, 32, 18, 47],
      'city': ['New York', 'Paris', 'London', 'Berlin']}
df1 = pd.DataFrame(data1)

data2 = {'name': ['Eva', 'Frank', 'Grace', 'Henry'],
      'age': [29, 23, 37, 31],
      'city': ['Rome', 'Sydney', 'Tokyo', 'Moscow']}
df2 = pd.DataFrame(data2)

In [34]:
# 進行加法
print(df1 + df2)

#當DataFrame物件進行算術運算時，如果兩個物件相對應的位置都存在值，則進行運算；否則，該位置的值為NaN

           name  age          city
0      AliceEva   54  New YorkRome
1      BobFrank   55   ParisSydney
2  CharlieGrace   55   LondonTokyo
3    DavidHenry   78  BerlinMoscow

In [42]:
# DataFrame物件可以按照指定的列或行進行排序
# 創建一個DataFrame物件
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
     'age': [25, 32, 18, 47],
     'city': ['New York', 'Paris', 'London', 'Berlin']}

df = pd.DataFrame(data)
# 按照age列進行排序，預設為升序排序
print(df.sort_values(by='age'))
print('--------------------------')
# 按照age列進行降序排序
print(df.sort_values(by='age', ascending=False))
print('--------------------------')
# 按照索引進行排序 >> 預設
print(df.sort_index())

      name  age      city
2  Charlie   18    London
0    Alice   25  New York
1      Bob   32     Paris
3    David   47    Berlin
--------------------------
      name  age      city
3    David   47    Berlin
1      Bob   32     Paris
0    Alice   25  New York
2  Charlie   18    London
--------------------------
      name  age      city
0    Alice   25  New York
1      Bob   32     Paris
2  Charlie   18    London
3    David   47    Berlin

###DataFrame 資料合併與重組

---

DataFrame物件可以根據指定的條件將不同的DataFrame物件合併在一起



* concat()
* merge()
* join()

####concat()

---
使用 concat() 方法可以將多個DataFrame物件沿著指定的軸合併在一起

In [44]:
# 創建兩個DataFrame物件
data1 = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
      'age': [25, 32, 18, 47],
      'city': ['New York', 'Paris', 'London', 'Berlin']}
df1 = pd.DataFrame(data1)

data2 = {'name': ['Eva', 'Frank', 'Grace', 'Henry'],
      'age': [29, 23, 37, 31],
      'city': ['Rome', 'Sydney', 'Tokyo', 'Moscow']}
df2 = pd.DataFrame(data2)

# 沿著列軸合併
print(pd.concat([df1, df2], axis=0))

      name  age      city
0    Alice   25  New York
1      Bob   32     Paris
2  Charlie   18    London
3    David   47    Berlin
0      Eva   29      Rome
1    Frank   23    Sydney
2    Grace   37     Tokyo
3    Henry   31    Moscow

In [45]:
# 沿著行軸合併
print(pd.concat([df1, df2], axis=1))

      name  age      city   name  age    city
0    Alice   25  New York    Eva   29    Rome
1      Bob   32     Paris  Frank   23  Sydney
2  Charlie   18    London  Grace   37   Tokyo
3    David   47    Berlin  Henry   31  Moscow

####merge()

---
根據指定的欄位將兩個DataFrame物件合併在一起

In [47]:
# 創建兩個DataFrame物件
data1 = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
      'age': [25, 32, 18, 47],
      'city': ['New York', 'Paris', 'London', 'Berlin']}
df1 = pd.DataFrame(data1)

data2 = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
     'salary': [5000, 6000, 7000, 8000]}
df2 = pd.DataFrame(data2)

In [48]:
# 根據name欄位合併
print(pd.merge(df1, df2, on='name'))

      name  age      city  salary
0    Alice   25  New York    5000
1      Bob   32     Paris    6000
2  Charlie   18    London    7000
3    David   47    Berlin    8000

####join()

---
將兩個DataFrame物件按照索引合併在一起

In [49]:
# 創建兩個DataFrame物件
data1 = {'age': [25, 32, 18, 47],
      'city': ['New York', 'Paris', 'London', 'Berlin']}
df1 = pd.DataFrame(data1, index=['Alice', 'Bob', 'Charlie', 'David'])

data2 = {'salary': [5000, 6000, 7000, 8000]}
df2 = pd.DataFrame(data2, index=['Alice', 'Bob', 'Charlie', 'David'])

In [50]:
# 按照索引合併
print(df1.join(df2))

         age      city  salary
Alice     25  New York    5000
Bob       32     Paris    6000
Charlie   18    London    7000
David     47    Berlin    8000

####Groupby()

---

Groupby 是一個非常有用的功能，用於將 DataFrame 分組後對每個組進行操作

In [52]:
data = {'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank'],
     'age': [25, 32, 18, 47, 23, 31],
     'gender': ['female', 'male', 'female', 'male', 'female', 'male'],
     'city': ['New York', 'Paris', 'London', 'Berlin', 'New York', 'Paris'],
     'salary': [50000, 80000, 25000, 100000, 35000, 75000]}
df = pd.DataFrame(data)
df

      name  age  gender      city  salary
0    Alice   25  female  New York   50000
1      Bob   32    male     Paris   80000
2  Charlie   18  female    London   25000
3    David   47    male    Berlin  100000
4     Emma   23  female  New York   35000
5    Frank   31    male     Paris   75000

In [53]:
# 按照 "city" 列的值進行分組，並對每個城市的人口數、平均年齡、平均薪資進行統計分析
grouped = df.groupby('city')
result = grouped.agg({'name': 'count', 'age': 'mean', 'salary': 'mean'})
print(result)

          name   age    salary
city
Berlin       1  47.0  100000.0
London       1  18.0   25000.0
New York     2  24.0   42500.0
Paris        2  31.5   77500.0

In [54]:
grouped = df.groupby(['city', 'gender'])
result = grouped.agg({'name': 'count', 'age': 'mean', 'salary': 'mean'})
print(result)

                 name   age    salary
city     gender
Berlin   male       1  47.0  100000.0
London   female     1  18.0   25000.0
New York female     2  24.0   42500.0
Paris    male       2  31.5   77500.0

#延伸閱讀

---

* [What kind of data does pandas handle?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html)

* [How do I read and write tabular data?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/02_read_write.html)

* [How do I select a subset of a DataFrame?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html)

* [How to create plots in pandas?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/04_plotting.html)

* [How to create new columns derived from existing columns?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/05_add_columns.html)

* [How to calculate summary statistics?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/06_calculate_statistics.html)

* [How to reshape the layout of tables?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/07_reshape_table_layout.html)

* [How to combine data from multiple tables?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/08_combine_dataframes.html) ← 這個以前為必修教材

* [How to handle time series data with ease?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/09_timeseries.html) ← 選修

* [How to manipulate textual data?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/10_text_data.html) ← 選修

* [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html) ← 必修